# Adding Resilience4j configuration for circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      service2:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 2
        waitDurationInOpenState: 10s
        failureRateThreshold: 50  
  

